<?php
/**
 * Domain routing: the generated ICS route, suppression of native WP-user
 * author archives (ADR 0037 §5) and activation/upgrade rewrite handling
 * (flush only on activation or versioned upgrade — never per request).
 *
 * @package Camino_Del_Dharma_Core
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Registers the generated-calendar route: /eventos/ical/{slug}.ics
 * (OWN-009: generated on request, never stored in the Media Library).
 * Top priority so the event single rules never swallow /eventos/ical/.
 */
function cdd_core_register_rewrites() {
	add_rewrite_rule( '^eventos/ical/([^/]+)\.ics$', 'index.php?cdd_core_event_ics=$matches[1]', 'top' );
}

/**
 * Registers the plugin query vars.
 *
 * @param array $query_vars Public query vars.
 */
function cdd_core_register_query_vars( $query_vars ) {
	$query_vars[] = 'cdd_core_event_ics';

	return $query_vars;
}

/**
 * Drops the rewrite rules of native WP-user author archives; the /author
 * URL space belongs to the blog_author CPT (ADR 0037 §5).
 *
 * @param array $rules Author rewrite rules.
 */
function cdd_core_disable_user_author_rewrites( $rules ) { // phpcs:ignore Generic.CodeAnalysis.UnusedFunctionParameter.Found -- filter signature.
	return array();
}

/**
 * Turns any remaining WP-user author request (e.g. /?author=N) into a
 * real 404 before the main query runs.
 *
 * @param array $query_vars Parsed request query vars.
 */
function cdd_core_block_user_author_requests( $query_vars ) {
	if ( isset( $query_vars['author'] ) || isset( $query_vars['author_name'] ) ) {
		return array( 'error' => '404' );
	}

	return $query_vars;
}

/**
 * Serves the generated .ics response for the ICS route.
 */
function cdd_core_serve_event_ics() {
	$slug = get_query_var( 'cdd_core_event_ics' );
	if ( '' === $slug ) {
		return;
	}

	$response = cdd_core_event_ics_response( sanitize_title( $slug ) );

	status_header( $response['status'] );
	foreach ( $response['headers'] as $name => $value ) {
		header( $name . ': ' . $value );
	}
	if ( '' !== $response['body'] ) {
		echo $response['body']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- text/calendar payload generated by the plugin, not HTML.
	}
	exit;
}

/**
 * Activation: register the domain objects, grant capabilities and flush
 * rewrites once. Never touches existing content (legacy posts without the
 * authors relationship stay published — ADR 0037 §7).
 */
function cdd_core_activate() {
	cdd_core_register_post_types();
	cdd_core_register_taxonomies();
	cdd_core_register_rewrites();
	cdd_core_grant_capabilities();
	flush_rewrite_rules();
	update_option( 'cdd_core_version', CDD_CORE_VERSION );
}

/**
 * Versioned upgrade: when the stored plugin version is behind, re-grant
 * capabilities and flush rewrites once (an already-active install never
 * re-runs activation).
 */
function cdd_core_maybe_upgrade() {
	if ( CDD_CORE_VERSION === get_option( 'cdd_core_version' ) ) {
		return;
	}

	cdd_core_grant_capabilities();
	flush_rewrite_rules();
	update_option( 'cdd_core_version', CDD_CORE_VERSION );
}
